## Broadcasting in NumPy array

In [1]:
import numpy as np
x1 = np.array([1,2,3,4])
x2 = np.array([1,2,3,4])
print(x1+x2)

[2 4 6 8]


In [2]:
var = np.array([[1],[2],[3]])
print(var)
print(var.ndim)
print(var.shape)

[[1]
 [2]
 [3]]
2
(3, 1)


In [3]:
import numpy as np
x1 = np.array([1,2,3])

var = np.array([[1],[2],[3]])

print(x1)
print()
print(var)
print()
print(x1+var)

[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
x = np.array([[1],[2]])
y = np.array([[1,2,3],[1,2,3]])
print(x+y)

[[2 3 4]
 [3 4 5]]
