## How to create NumPy array

To create a NumPy array you can use the function np.array()

In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

y = np.array(x)
print(y)
print(type(y))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [2]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [3]:
l=[]

for i in range(1, 5):
    int_1 = int(input("Enter any number : "))
    l.append(int_1)
    
print(np.array(l))

[12 24  6 32]


ndim :- ndim method check the array is one dimension or two dimension

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

y = np.array(x)
print(y)
print(type(y))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


1-D Array

2-D Array

3-D Array

Multidimensional Array

2-D Array

In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

x = np.array(arr2)
print(x)
print(f"The array is {x.ndim} dimension")

[[1 2 3 4]
 [5 6 7 8]]
The array is 2 dimension


In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


3-D Array

In [7]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

y = np.array(arr3)
print(y)
print(y.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


How to create multimdimension array

In [8]:
md = np.array([1,2,3,4,5], ndmin=10)
print(md)
print(md.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
