## How to create NumPy array with random number

1. rand() :- the function is used to generate a random value between 0 to 1

2. randn() :- the function is used to generate a random value closed to zero. This may return positive or negative number as well.

3. ranf() :- th function for doing random sampling in numpy. It return an array of specified shape and fill it with random float in the half open interval [0.0, 1.0]

4. randint() :- the function is used to generate number between a given range.

rand()

In [1]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.rand(4)
print(ran)

[0.44270084 0.09449855 0.07783142 0.50083753]


In [2]:
## 2-D array it give random number everytime
import numpy as np

ran = np.random.rand(3,5)
print(ran)

[[0.43234126 0.31694721 0.72149771 0.0742577  0.28207658]
 [0.05514931 0.06420471 0.67455775 0.60203762 0.22043157]
 [0.0399057  0.62462737 0.80676458 0.71504828 0.61779457]]


randn()

In [3]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.randn(4)
print(ran)

[ 0.78075345 -0.2203575   0.1090741  -0.87243281]


ranf()

In [4]:
## 1-D array it give random number everytime
import numpy as np

ran = np.random.ranf(4)
print(ran)

[0.12967001 0.36008897 0.6500597  0.98463686]


randint()

In [5]:
## It generate a random number betwee max,min,total_value
import numpy as np

##ran = np.random.randint(min,max,total_value)
ran = np.random.randint(4,20,5)
print(ran)

[13 13  6 11  9]
