## Arithmatic operation in NumPy array

a+b = np.add(a,b)

a-b = np.subtract(a,b)

a*b = np.multiply(a,b)

a/b = np.devide(a,b)

a%b = np.mod(a,b)

a**b = np.power(a,b)

1/a = np.reciprocal(a,b)

Addition using add method

In [1]:
import numpy as np

var = np.array([1,2,3,4,5])

x = var + 3

print(x)

[4 5 6 7 8]


In [2]:
import numpy as np

var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

x = np.add(var1,var2)

print(x)

[ 2  4  6  8 10]


In [3]:
import numpy as np

var1 = np.array([1,2,3,4,5])
var2 = np.array([2,4,5,1,3])

x = var1+var2

print(x)

[3 6 8 5 8]


Multipliactio using multiply() method

In [4]:
import numpy as np

var1 = np.array([1,2,3,4,5])

x = var1*3

print(x)

[ 3  6  9 12 15]


In [5]:
import numpy as np

var1 = np.array([1,2,3,4,5])
var2 = np.array([8,2,3,6,1])

x = np.multiply(var1,var2)

print(x)

[ 8  4  9 24  5]


Devide using devide() method

In [6]:
import numpy as np

var1 = np.array([1,2,3,4,5])

x = var1/2

print(x)

[0.5 1.  1.5 2.  2.5]


In [7]:
import numpy as np

var1 = np.array([4,24,8,9])
var2 = np.array([2,3,2,3])

x = np.divide(var1,var2)

print(x)

[2. 8. 4. 3.]


Modulus

In [8]:
import numpy as np

var1 = np.array([1,2,3,4,5])

x = var%2

print(x)

[1 0 1 0 1]


In [9]:
import numpy as np

var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

x = np.add(var1,var2)

print(x)

[ 2  4  6  8 10]


2-D Array 

In [10]:
import numpy as np

var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[3,4,2,6],[3,2,1,9]])

print(var1)
print(var2)
print()
x = var1+var2
print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[3 4 2 6]
 [3 2 1 9]]

[[ 4  6  5 10]
 [ 8  8  8 17]]


In [11]:
import numpy as np

var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[3,4,2,6],[3,2,1,9]])

x = np.add(var1,var2)

print(x)

[[ 4  6  5 10]
 [ 8  8  8 17]]


reciprocal

In [12]:
import numpy as np

var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[3,4,2,6],[3,2,1,9]])

x = np.reciprocal(var1,var2)

print(x)

[[1 0 0 0]
 [0 0 0 0]]


In [13]:
import numpy as np

var1 = np.array([1,2,3,4,5])

x = np.reciprocal(var1)

print(x)

[1 0 0 0 0]


Power method

In [14]:
import numpy as np

var1 = np.array([1,2,3,4,5])

x = var1**3

print(x)

[  1   8  27  64 125]


In [15]:
import numpy as np

var1 = np.array([[1,2,3,4],[5,6,7,8]])
var2 = np.array([[3,4,2,3],[3,2,1,3]])

x = np.pow(var1,var2)

print(x)

[[  1  16   9  64]
 [125  36   7 512]]
